repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.11
        args: ["--profile", "black", "--line-length=79"]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place", "--recursive"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       args: ['--config=.flake8']

  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: check types
  #       entry: mypy
  #       language: python
  #       args: [--python-version=3.11]
  #       additional_dependencies: [pydantic, pytest]
  #       verbose: true
  #       exclude: '^tests/test_data|^pyproject.toml|^poetry.lock|^.pre-commit-config.yaml|^.gitignore|^mypy.ini|^.venv|^azure-pipelines.yaml|^.flake8|^notebooks/|pytest.ini|README.md|^docs|^azure-pipeline.yaml'

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        pass_filenames: false
