name: Code Quality Linux

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Code Quality Linux
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        run: pipx install uv

      - name: Load cached dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.11-${{ hashFiles('**/uv.lock') }}

      - name: Create virtual environment and install dependencies
        run: |
          uv venv --python=3.11 .venv  # Explicitly use Python 3.11
          uv pip sync  # Sync dependencies from uv.lock

      - name: Test with pytest
        run: |
          uv venv exec pytest --junitxml=junit/test-results.xml --nbmake --nbmake-kernel=python3 -n auto --cov=openspoor --cov-fail-under=50 tests/ demo_notebook/
