name: Code Quality Windows

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Code Quality Windows
    runs-on: "windows-latest"
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        run: pipx install uv

      - name: Load cached dependencies
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.11-${{ hashFiles('**/uv.lock') }}

      - name: Create virtual environment and install dependencies (if cache is missing)
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          uv venv --python=3.11
          source .venv/Scripts/activate
          uv sync

      - name: Test with pytest
        run: |
          uv run pytest --junitxml=junit/test-results.xml --nbmake --nbmake-kernel=python3 -n auto --cov=openspoor --cov-fail-under=50 tests/ demo_notebook/
