name: Code Quality Linux

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Code Quality Linux
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          poetry install --no-dev  # Install main dependencies
          poetry install --dev  # Install development dependencies

      - name: Test with pytest
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --nbmake --nbmake-kernel=python3 -n auto --cov=openspoor --cov-fail-under=50 tests/ demo_notebook/
