# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Code Quality Linux

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Code Quality Linux
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ".[dev]"

      - name: Test with pytest
        run: |
          pytest --junitxml=junit/test-results.xml --nbmake --nbmake-kernel=python3 -n auto --cov=openspoor --cov-fail-under=50 tests/ demo_notebook/
